package me.daddychurchill.CityWorld.api;

/** What {@link CityWorldAPI#reserveSite} did. Only {@link #RESERVED} changed anything. */
public enum SiteResult {
    /** The site is reserved and saved with the world; its chunks will plan as open, level ground. */
    RESERVED,
    /** The level is not generated by CityWorld. */
    NOT_CITYWORLD,
    /** A radius outside 0..{@link CityWorldAPI#MAX_SITE_RADIUS}, or a height outside the world. */
    INVALID,
    /** The site or its blend ring covers part of a vault, which it would have cut away. Nothing reserved. */
    OVERLAPS_VAULT,
    /** Re-planning with the site moved or removed a vault entrance nearby, so it was rolled back. Nothing reserved. */
    VAULT_MOVED
}
