#!/usr/bin/env bash
# Publish the user-facing docs to the GitHub wiki.
#
#   scripts/gen-wiki.sh            # clone/refresh the wiki, write the pages, show the diff
#   scripts/gen-wiki.sh --push     # ...and push it
#
# Pages this script does not write are left alone, so hand-written pages (Welcome-to-City-17) survive
# and can be linked from Home. Only the generated pages below are overwritten.
#
# ⚠ The repo is the source of truth. The wiki is GENERATED, never hand-edited: a hand-kept copy of a
# 413-line configuration doc drifts from the real one, and a wiki that quietly disagrees with the mod
# is worse than no wiki. Anything typed into the wiki by hand is overwritten by the next run, so edit
# the file in the repo and re-run this.
#
# ⚠ GitHub does not create the wiki's git repo until the FIRST page is saved through the web UI. Until
# then the clone fails with "Repository not found", which looks exactly like a permissions problem and
# is not. Create any page at <repo>/wiki once, then this works forever.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WIKI_URL="${CITYWORLD_WIKI_URL:-https://github.com/Sablednah/CityWorld-ReForged.wiki.git}"
WORK="${CITYWORLD_WIKI_DIR:-$ROOT/build/wiki}"
PUSH=0
[ "${1:-}" = "--push" ] && PUSH=1

if [ -d "$WORK/.git" ]; then
    git -C "$WORK" fetch --quiet origin && git -C "$WORK" reset --quiet --hard origin/master 2>/dev/null \
        || git -C "$WORK" reset --quiet --hard origin/main
else
    rm -rf "$WORK"
    if ! git clone --quiet "$WIKI_URL" "$WORK" 2>/dev/null; then
        cat >&2 <<'MSG'
!! Could not clone the wiki.
!! GitHub creates the wiki repository only after its FIRST page is saved in the web UI.
!! Open <repo>/wiki, click "Create the first page", save anything, then re-run this.
MSG
        exit 1
    fi
fi

# repo file -> wiki page name. The wiki turns a page name into its URL, so the names are the URLs.
emit() {
    local src="$1" page="$2" blurb="$3"
    {
        printf '%s\n\n' "$blurb"
        printf '%s\n' '<!-- GENERATED by scripts/gen-wiki.sh from the repository. Do not edit here: the next'
        printf '%s\n\n' '     run overwrites it. Edit the source file in the repo instead. -->'
        cat "$ROOT/$src"
    } > "$WORK/$page.md"
    printf '  %-34s -> %s.md\n' "$src" "$page"
}

emit CURSEFORGE-CONFIGURATION.md "Configuring-CityWorld" \
    "> Every setting, how to set them, and worked recipes. Source: \`CURSEFORGE-CONFIGURATION.md\`."
emit CURSEFORGE-COMMANDS.md      "Commands" \
    "> Every command and what it is for. Source: \`CURSEFORGE-COMMANDS.md\`."
emit PALETTES.md                 "Building-Palettes" \
    "> Which blocks build the cities, and how to add your own mod's. Source: \`PALETTES.md\`."
emit NODES.md                    "Permission-Nodes" \
    "> Permission nodes for servers. Source: \`NODES.md\`."

cat > "$WORK/Home.md" <<'HOME'
# CityWorld ReForged

> *"You have chosen, or been chosen, to relocate to one of our finest remaining urban centers."*
> — [Welcome to City 17](Welcome-to-City-17)

Procedurally generated cities for Minecraft — NeoForge on 1.21.1, 1.21.11, 26.1, 26.2 and 26.3, and
MinecraftForge on 1.20.1.

<!-- GENERATED by scripts/gen-wiki.sh from the repository. Do not edit here. -->

## Advanced configuration

- **[Configuring CityWorld](Configuring-CityWorld)** — all ~100 settings, the three ways to set them,
  and worked recipes. Start here.
  - [Villages and other vanilla structures](Configuring-CityWorld#recipes) — CityWorld suppresses
    vanilla structures so it can own the chunk; one small datapack turns them back on.
  - [Your other mods' blocks and biomes](Configuring-CityWorld#full-settings-reference)
- **[Building Palettes](Building-Palettes)** — which blocks build the cities, and how to add your own.
- **[Commands](Commands)** — including `/cwlocate`, which is the quickest way to tell whether a
  datapack change actually took effect.
- **[Permission Nodes](Permission-Nodes)** — for servers.

## Elsewhere

- [Changelog](https://github.com/Sablednah/CityWorld-ReForged/blob/master/CHANGELOG.md)
- [CurseForge](https://www.curseforge.com/minecraft/mc-mods/cityworld-reforged) ·
  [Modrinth](https://modrinth.com/mod/cityworld-reforged) ·
  [sablecraft.co.uk](https://sablecraft.co.uk/cityworld-reforged/)

> Settings and terrain changes only affect **newly generated chunks** — existing chunks never
> regenerate, so a fresh world (or unexplored land) is needed to see worldgen changes.
HOME
printf '  %-34s -> %s\n' "(written here)" "Home.md"

echo
git -C "$WORK" add -A
if git -C "$WORK" diff --cached --quiet; then
    echo ">> Wiki already matches the repo — nothing to publish."
    exit 0
fi
git -C "$WORK" diff --cached --stat | sed 's/^/  /'
if [ "$PUSH" = 1 ]; then
    git -C "$WORK" -c user.name=Sablednah commit -q -m "Regenerate from the repository docs"
    git -C "$WORK" push --quiet origin HEAD
    echo ">> Pushed."
else
    echo ">> Not pushed. Re-run with --push when the diff looks right."
fi
