package me.daddychurchill.CityWorld;

import java.util.Locale;
import java.util.Set;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.exceptions.CommandSyntaxException;

import me.daddychurchill.CityWorld.Clipboard.Clipboard;
import me.daddychurchill.CityWorld.Clipboard.ClipboardLot;
import me.daddychurchill.CityWorld.Clipboard.SchematicLibrary;
import me.daddychurchill.CityWorld.Context.DataContext;
import me.daddychurchill.CityWorld.Plats.PlatLot;
import me.daddychurchill.CityWorld.Support.PlatMap;
import me.daddychurchill.CityWorld.worldgen.CityWorldChunkGenerator;

import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.core.registries.Registries;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Relative;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.levelgen.Heightmap;

/**
 * The CityWorld command tree — the modern Brigadier port of upstream's {@code CommandCityWorld} /
 * {@code CommandCityInfo} / {@code CommandCityChunk}.
 *
 * <ul>
 *   <li>{@code /cityinfo} — anyone. Reports the plan under the player: context, lot, and how the
 *       planner graded the terrain. Read-only. (Originally contributed to upstream by Sablednah,
 *       PR #4; that attribution is preserved here.)</li>
 *   <li>{@code /cityworld} / {@code /cityworld leave} — op. Teleports into the {@code cityworld:city}
 *       dimension (and back to the overworld), landing on the surface at the player's X/Z.</li>
 * </ul>
 *
 * <p>{@code /citychunk} is intentionally not ported: its {@code regen} relied on Bukkit's runtime
 * {@code World.regenerateChunk}, which modern Minecraft has no safe equivalent for (chunks can only
 * be reset by deleting region files while the world is unloaded).
 */
public final class CityWorldCommands {

    /** The dimension registered in {@code data/cityworld/dimension/city.json}. */
    private static final ResourceKey<Level> CITY = ResourceKey.create(Registries.DIMENSION,
            Identifier.fromNamespaceAndPath(CityWorldMod.MODID, "city"));

    private CityWorldCommands() {}

    public static void register(CommandDispatcher<CommandSourceStack> dispatcher) {
        dispatcher.register(Commands.literal("cityinfo")
                .executes(CityWorldCommands::cityInfo));

        dispatcher.register(Commands.literal("cityworld")
                .requires(Commands.hasPermission(Commands.LEVEL_GAMEMASTERS))
                .executes(ctx -> teleport(ctx, CITY, "Entering the city..."))
                .then(Commands.literal("leave")
                        .executes(ctx -> teleport(ctx, Level.OVERWORLD, "Leaving CityWorld... come back soon!"))));

        dispatcher.register(Commands.literal("cityschem")
                .requires(Commands.hasPermission(Commands.LEVEL_GAMEMASTERS))
                .then(Commands.literal("list")
                        .executes(CityWorldCommands::listSchematics))
                .then(Commands.argument("name", StringArgumentType.greedyString())
                        .executes(CityWorldCommands::pasteSchematic)));

        dispatcher.register(Commands.literal("cityfind")
                .requires(Commands.hasPermission(Commands.LEVEL_GAMEMASTERS))
                .then(Commands.argument("name", StringArgumentType.greedyString())
                        .executes(CityWorldCommands::findSchematic)));
    }

    // ------------------------------------------------------------------ /cityinfo

    private static int cityInfo(CommandContext<CommandSourceStack> ctx) throws CommandSyntaxException {
        ServerPlayer player = ctx.getSource().getPlayerOrException();
        ServerLevel level = player.level();

        ChunkGenerator generator = level.getChunkSource().getGenerator();
        if (!(generator instanceof CityWorldChunkGenerator cityGenerator)) {
            ctx.getSource().sendFailure(Component.literal("This world is not generated by CityWorld."));
            return 0;
        }

        ChunkPos pos = player.chunkPosition();
        CityWorldGenerator context = cityGenerator.getContext(level);
        PlatMap platmap = context.getPlatMap(pos.x, pos.z);
        PlatLot lot = platmap.getMapLot(pos.x, pos.z);
        DataContext dataContext = platmap.context;

        line(ctx, "at", "chunk " + pos.x + ", " + pos.z);
        line(ctx, "context", dataContext.getClass().getSimpleName()
                + " (" + dataContext.getSchematicFamily() + ")");
        line(ctx, "lot", lot.getClass().getSimpleName() + " (" + lot.style + ")");
        if (lot instanceof ClipboardLot clipLot)
            line(ctx, "schematic", clipLot.getClip().name + " [" + clipLot.getClip().family + "]");
        line(ctx, "nature", String.format("%.0f%%", platmap.getNaturePercent() * 100.0));
        return 1;
    }

    private static void line(CommandContext<CommandSourceStack> ctx, String key, String value) {
        ctx.getSource().sendSuccess(() -> Component.literal(key + ": " + value), false);
    }

    // ------------------------------------------------------------------ /cityschem <name>

    private static int pasteSchematic(CommandContext<CommandSourceStack> ctx) throws CommandSyntaxException {
        ServerPlayer player = ctx.getSource().getPlayerOrException();
        ServerLevel level = player.level();
        String name = StringArgumentType.getString(ctx, "name");

        Clipboard clip = SchematicLibrary.get(name);
        if (clip == null) {
            ctx.getSource().sendFailure(Component.literal(
                    "No classic schematic named '" + name + "'. Try /cityschem list."));
            return 0;
        }

        BlockPos at = player.blockPosition();
        clip.paste(level, at.getX(), at.getY(), at.getZ(), level.getRandom());
        ctx.getSource().sendSuccess(() -> Component.literal(
                "Pasted '" + clip.name + "' [" + clip.family + "] (" + clip.sizeX + "x" + clip.sizeY + "x"
                        + clip.sizeZ + ") at " + at.getX() + ", " + at.getY() + ", " + at.getZ()), true);
        return 1;
    }

    private static int listSchematics(CommandContext<CommandSourceStack> ctx) {
        java.util.List<String> names = SchematicLibrary.names();
        ctx.getSource().sendSuccess(() -> Component.literal(
                names.size() + " classic schematics: " + String.join(", ", names)), false);
        return 1;
    }

    // ------------------------------------------------------------------ /cityfind <name>

    /** Where a matching building was found. */
    private record Found(String name, String family, int x, int z, double dist, String compass) {}

    /** Rings of platmaps to search out from the player before giving up (10 chunks each). */
    private static final int FIND_MAX_RINGS = 12;

    private static int findSchematic(CommandContext<CommandSourceStack> ctx) throws CommandSyntaxException {
        ServerPlayer player = ctx.getSource().getPlayerOrException();
        ServerLevel level = player.level();
        MinecraftServer server = ctx.getSource().getServer();
        String query = StringArgumentType.getString(ctx, "name").trim();

        ChunkGenerator generator = level.getChunkSource().getGenerator();
        if (!(generator instanceof CityWorldChunkGenerator cityGenerator)) {
            ctx.getSource().sendFailure(Component.literal("This world is not generated by CityWorld."));
            return 0;
        }
        CityWorldGenerator context = cityGenerator.getContext(level);
        ChunkPos pos = player.chunkPosition();
        double playerX = player.getX();
        double playerZ = player.getZ();

        ctx.getSource().sendSuccess(() -> Component.literal("Searching for '" + query + "'..."), false);

        // Planning is off-thread (a wide sweep can plan hundreds of platmaps — too slow for the server
        // thread's tick watchdog). getPlatMap is deterministic and thread-safe, so this is safe; the
        // result is delivered back on the server thread via server.execute.
        Thread t = new Thread(() -> {
            Found best = search(context, query, pos.x, pos.z, playerX, playerZ);
            server.execute(() -> {
                if (best == null)
                    player.sendSystemMessage(Component.literal("Found no '" + query + "' within "
                            + (FIND_MAX_RINGS * PlatMap.Width * 16) + " blocks."));
                else
                    player.sendSystemMessage(Component.literal("Nearest '" + best.name() + "' [" + best.family()
                            + "] at x=" + best.x() + " z=" + best.z() + "  (" + Math.round(best.dist())
                            + " blocks " + best.compass() + ")"));
            });
        }, "cityworld-find");
        t.setDaemon(true);
        t.start();
        return 1;
    }

    private static Found search(CityWorldGenerator context, String query, int px, int pz,
            double playerX, double playerZ) {
        String q = query.toLowerCase(Locale.ROOT);
        int pmX0 = Math.floorDiv(px, PlatMap.Width) * PlatMap.Width;
        int pmZ0 = Math.floorDiv(pz, PlatMap.Width) * PlatMap.Width;
        Found best = null;
        int foundRing = -1;
        for (int r = 0; r <= FIND_MAX_RINGS; r++) {
            for (int dx = -r; dx <= r; dx++) {
                for (int dz = -r; dz <= r; dz++) {
                    if (Math.max(Math.abs(dx), Math.abs(dz)) != r)
                        continue; // only the outer ring at radius r
                    PlatMap pm = context.getPlatMap(pmX0 + dx * PlatMap.Width, pmZ0 + dz * PlatMap.Width);
                    Found hit = scanPlatMap(pm, q, playerX, playerZ);
                    if (hit != null && (best == null || hit.dist() < best.dist()))
                        best = hit;
                }
            }
            if (best != null && foundRing < 0)
                foundRing = r;
            // once found, scan one more ring (a nearer one can sit in an adjacent platmap), then stop
            if (foundRing >= 0 && r >= foundRing + 1)
                break;
        }
        return best;
    }

    private static Found scanPlatMap(PlatMap pm, String q, double playerX, double playerZ) {
        Found best = null;
        for (int x = 0; x < PlatMap.Width; x++) {
            for (int z = 0; z < PlatMap.Width; z++) {
                if (pm.getLot(x, z) instanceof ClipboardLot clip
                        && clip.getClip().name.toLowerCase(Locale.ROOT).contains(q)) {
                    int wx = clip.getChunkX() * 16 + 8;
                    int wz = clip.getChunkZ() * 16 + 8;
                    double dist = Math.hypot(wx - playerX, wz - playerZ);
                    if (best == null || dist < best.dist())
                        best = new Found(clip.getClip().name, clip.getClip().family.name(), wx, wz, dist,
                                compass(wx - playerX, wz - playerZ));
                }
            }
        }
        return best;
    }

    private static String compass(double dx, double dz) {
        // Minecraft axes: +X is east, +Z is south.
        String ns = dz < -8 ? "N" : dz > 8 ? "S" : "";
        String ew = dx < -8 ? "W" : dx > 8 ? "E" : "";
        String dir = ns + ew;
        return dir.isEmpty() ? "here" : dir;
    }

    // ------------------------------------------------------------------ /cityworld [leave]

    private static int teleport(CommandContext<CommandSourceStack> ctx, ResourceKey<Level> destination,
            String message) throws CommandSyntaxException {
        ServerPlayer player = ctx.getSource().getPlayerOrException();
        MinecraftServer server = ctx.getSource().getServer();

        ServerLevel target = server.getLevel(destination);
        if (target == null) {
            ctx.getSource().sendFailure(Component.literal(
                    "Destination dimension " + destination.identifier() + " is not loaded."));
            return 0;
        }
        if (player.level() == target) {
            ctx.getSource().sendFailure(Component.literal("You are already there."));
            return 0;
        }

        // Keep the player's horizontal position; drop them onto the surface at the destination. Force
        // the chunk to generate first so the heightmap is real rather than a default.
        int x = player.getBlockX();
        int z = player.getBlockZ();
        target.getChunk(x >> 4, z >> 4);
        int y = target.getHeight(Heightmap.Types.MOTION_BLOCKING, x, z);

        ctx.getSource().sendSuccess(() -> Component.literal(message), false);
        player.teleportTo(target, x + 0.5, y, z + 0.5, Set.<Relative>of(), player.getYRot(), player.getXRot(), false);
        return 1;
    }
}
